include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - avoid_init_to_null
    - flutter_style_todos
    - prefer_const_declarations
    - avoid_empty_else
    - await_only_futures
    - avoid_void_async
    - avoid_unnecessary_containers
    - valid_regexps
    - prefer_if_null_operators
    - sort_unnamed_constructors_first
    - prefer_relative_imports

analyzer:
  plugins:
    - dart_code_metrics

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 10
    source-lines-of-code: 200

  metrics-exclude:
    - test/**

  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma:
        break-on: 3
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unused-parameters
    - double-literal-format
    - binary-expression-operand-order
    - member-ordering:
        #TODO
        order:
          - public-fields
          - constructors
          - private-fields
          - public-methods
          - private-methods
    - no-boolean-literal-compare
      #    - no-equal-arguments:
      #        ignored-parameters:
      #          - height
    #          - width
    - no-equal-then-else
    - always-remove-listener
    - avoid-returning-widgets
    - prefer-single-widget-per-file
    - prefer-extracting-callbacks:
        ignored-named-arguments:
          - onRefresh
          - builder
          - onWillPop
          - onPressed
          - onTap
    - avoid-returning-widgets:
        ignored-names:
          - _buildBody
        ignored-annotations:
          - allowedAnnotation
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - prefer-first
    - prefer-last
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
    - prefer-match-file-name:
        exclude:
          - test/**
    - prefer-correct-type-name:
        excluded: [ '' ]
        min-length: 3
        max-length: 50
    - avoid-unnecessary-setstate
    - prefer-const-border-radius