name: torys
flutter: 
  uses-material-design: true
  assets:
    - assets/images/
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    
  flutter_localizations: 
    sdk: flutter 

  cupertino_icons: ^1.0.2

  #injection
  get_it: ^7.2.0
  injectable: ^2.1.0
  freezed: ^2.3.2


  #ui
  carousel_slider: ^4.0.0
  sizer: ^2.0.15
  mask_text_input_formatter: ^2.4.0
  shimmer: ^2.0.0

  #storage
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0

  #architecture
  flutter_bloc: ^8.1.2
  

  #rx
  rxdart: ^0.27.3

  #network
  oauth2: ^2.0.0
  dio: ^5.0.1
  meta: ^1.8.0
  json_annotation: ^4.8.0
  either_dart: ^0.3.0

  #logging:
  logger: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #models
  equatable: ^2.0.5

  #linter
  flutter_lints: ^2.0.0

  #generation
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
