name: torys
flutter: 
  uses-material-design: true
  assets:
    - assets/svg/icons/
    - assets/svg/
    - assets/png/
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-14.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    
  flutter_localizations: 
    sdk: flutter 

  cupertino_icons: ^1.0.2

  #injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  freezed: ^1.1.1

  #ui
  carousel_slider: ^4.0.0
  flutter_svg: ^1.0.3

  #storage
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0

  #architecture
  flutter_bloc: ^7.2.0
  

  #rx
  rxdart: ^0.27.3

  #network
  http: ^0.13.4
  flutter_web_auth: ^0.4.0
  oauth2: ^2.0.0
  retrofit: '>=3.0.0 <4.0.0'
  dio: ^4.0.4
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #generation
  build_runner: ^2.1.7
  injectable_generator: ^1.5.3

  #retrofit
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.4