name: book_readers
flutter: 
  uses-material-design: true
  assets:
    - assets/images/
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
    
  flutter_localizations: 
    sdk: flutter 

  cupertino_icons: ^1.0.2

  #injection
  get_it: ^7.2.0
  injectable: ^2.1.0

  #code generation
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5


  #ui
  carousel_slider: ^4.0.0
  sizer: ^2.0.15
  mask_text_input_formatter: ^2.4.0
  shimmer: ^2.0.0

  #storage
  flutter_secure_storage: ^8.0.0

  #architecture
  flutter_bloc: ^8.1.2
  auto_route: ^6.0.5
  auto_route_generator: ^6.0.2

  #db
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path:
  #moor_generator: ^4.6.0

  #rx
  rxdart: ^0.27.3

  #network
  oauth2: ^2.0.0
  dio: ^5.0.1
  meta: ^1.8.0
  json_annotation: ^4.8.0
  either_dart: ^0.3.0

  #logging:
  logger: ^1.2.2
  animated_text_kit: ^4.2.2
  another_flushbar: ^1.12.29
  webview_flutter: ^4.2.0
  google_sign_in: ^6.1.0
  firebase_core: ^2.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  #models
  equatable: ^2.0.5

  #linter
  flutter_lints: ^2.0.0

  #generation
  build_runner: ^2.3.3
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1

  #db
  drift_dev: ^2.7.0
